### ISSUE TITLE
register.html

### ISSUE THREAD

**Issue by 0phidian** [HTS-Codeart/blog#3]
The name for the password form used for registration is the same as the name for the password form in the sidebar. In both name="password"

**Comment by Ninjex** [comment]
This brought my attention to another issue, but this itself is not an issue. I renamed the form on register.html to register, since it was named 'login' for some odd reason. The content inside each form will be sent to the specified php script for validation.

Register: form name="register" method="post" action="register.php"
Sidebar: form name="login" method="post" action="/members/login.php"

Everything contained inside the 'register' form tag will be sent off to register.php
Everything contained inside the 'login' form tag will be sent off to login.php

This should prevent any conflicts of the post data from the two separate forms.
